version: "3.9"

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "20m"
   max-file: "4"


services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    hostname: php-container
    volumes:
      - ./www:/var/www
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "curl http://nginx | grep 'works'"
      interval: 20s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    logging: *logging


  nginx:
    image: "nginx:stable"
    container_name: nginx
    hostname: nginx-container
    volumes:
      - ./www:/var/www
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      - app
    restart: unless-stopped
    logging: *logging


networks:
   app:
      driver: bridge
